// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const contentCard: string;
export const cardContainer: string;
export const pContainer: string;
export const footerCard: string;
export const avatar: string;
