// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const headerCard: string;
export const title: string;
export const subtitle: string;
export const buttonContainer: string;
export const button: string;
export const roundedButton: string;
export const roundedButtonText: string;
export const macImage: string;
