// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const ul: string;
export const li: string;
export const a: string;
export const nav: string;
export const roundedButton: string;
