// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const containerTitle: string;
export const cardContainer: string;
export const card: string;
export const cardHeader: string;
export const cardBody: string;
export const cardFooter: string;
export const listItem: string;
export const listItemTitle: string;
