// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const protectionCard: string;
export const button: string;
export const ml: string;
export const mr: string;
